workflows:
  ios-workflow:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    working_directory: freejobalert
    integrations:
      app_store_connect: CodeMagic API Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.freejobalert
        certificate: Automatic
      vars:
        APP_ID: 6756413069
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - christopher.selvin@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  ios-workflow-development:
    name: iOS Development Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    working_directory: freejobalert
    integrations:
      app_store_connect: CodeMagic API Key
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.freejobalert
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa (development)
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - christopher.selvin@gmail.com
        notify:
          success: true
          failure: true
